from dataclasses import dataclass
from typing import Dict, Annotated


from  biotite.structure import AtomArray
import jax
import jax.numpy as jnp

@jax.tree_util.register_dataclass
@dataclass(frozen=True)
class RotorTable:
    """Topology and ideal physical measurements for NeRF placed hydrogens."""
    target_idx: jnp.ndarray
    parent_idx: jnp.ndarray
    grandparent_idx: jnp.ndarray
    greatgrand_idx: jnp.ndarray
    ideal_r: jnp.ndarray
    ideal_theta: jnp.ndarray
    initial_chi: jnp.ndarray

@jax.tree_util.register_dataclass
@dataclass(frozen=True)
class HostEmbeddings:
    """Structural conditionings generated by the native Evoformer trunk."""
    pair: jnp.ndarray
    single: jnp.ndarray
    target_feat: Dict[str, jnp.ndarray]

@jax.tree_util.register_dataclass
@dataclass(frozen=True)
class AtomMapping:
    """Index trackers matching the Host layout to the full complex Oracle."""
    oracle_heavy: jnp.ndarray
    af3_source: jnp.ndarray
    num_oracle_atoms: int

@jax.tree_util.register_dataclass
@dataclass(frozen=True)
class WaterMapping:
    """Index trackers for SO(3) rigid-body water structures."""
    oxygen_source: jnp.ndarray
    h1_target: jnp.ndarray
    h2_target: jnp.ndarray

@jax.tree_util.register_dataclass
@dataclass(frozen=True)
class OracleMapping:
    """Unified behavioral domain model representing the complete all-atom molecular blueprint."""
    num_atoms: int
    heavy_indices: Annotated[jax.Array, int]
    source_indices: Annotated[jax.Array, int]
    initial_coordinates: Annotated[jax.Array, float]
    rotor_table: RotorTable
    water_mapping: WaterMapping

    @jax.jit
    def assemble_coordinates(
        self, x_af3_flat: jnp.ndarray, chi_angles: jnp.ndarray, water_rotations: jnp.ndarray
    ) -> jnp.ndarray:
        """Translates and kinematically expands Host backbone coordinates to full all-atom space."""

        # local imports break initialization cyclic dependency paths cleanly
        from .kinematics import generalized_nerf_layer, so3_water_layer

        x_full = self.initial_coordinates

        # heavy atoms tracked natively from the Host layout
        x_full = (x_full
            .at[self.heavy_indices]
            .set(
                x_af3_flat[self.source_indices]
                .reshape(self.heavy_indices.shape[0], 3)
            )
        )

        # kinematically place protons via NeRF layers
        if self.rotor_table.target_idx.shape[0] > 0:
            x_h = generalized_nerf_layer(x_af3_flat, self.rotor_table, chi_angles)
            x_h_reshaped = x_h.reshape((self.rotor_table.target_idx.shape[0], 3))
            x_full = x_full.at[self.rotor_table.target_idx].set(x_h_reshaped)

        # rotate explicit water structures via SO(3) layers
        if self.water_mapping.oxygen_source.shape[0] > 0:
            oxygen_coords = x_af3_flat[self.water_mapping.oxygen_source]
            h1, h2 = so3_water_layer(oxygen_coords, water_rotations)
            h1_reshaped = h1.reshape((self.water_mapping.h1_target.shape[0], 3))
            h2_reshaped = h2.reshape((self.water_mapping.h2_target.shape[0], 3))
            x_full = x_full.at[self.water_mapping.h1_target].set(h1_reshaped)
            x_full = x_full.at[self.water_mapping.h2_target].set(h2_reshaped)

        return x_full

@dataclass
class Oracle:
    mapping: OracleMapping
    atoms: AtomArray

@jax.tree_util.register_dataclass
@dataclass(frozen=True)
class Conformation:
    atom_positions: jnp.ndarray # [num_atoms, 3]
    chi_angles: jnp.ndarray # [chi_angles]
    water_rotations: jnp.ndarray # [num_waters, 3]

@jax.tree_util.register_dataclass
@dataclass(frozen=True)
class Conformations:
    atom_positions: jnp.ndarray # [B, num_atoms, 3]
    chi_angles: jnp.ndarray # [B, chi_angles]
    water_rotations: jnp.ndarray # [B, num_waters, 3]

    # aos indexing
    def __getitem__(self, index):
        return Conformation(
            self.atom_positions[index],
            self.chi_angles[index],
            self.water_rotations[index],
        )

    # aos iteration
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]
        
