from dataclasses import dataclass
from typing import Dict
import jax
import jax.numpy as jnp

@jax.tree_util.register_dataclass
@dataclass(frozen=True)
class RotorTable:
    """Topology and ideal physical measurements for NeRF placed hydrogens."""
    target_idx: jnp.ndarray
    parent_idx: jnp.ndarray
    grandparent_idx: jnp.ndarray
    greatgrand_idx: jnp.ndarray
    ideal_r: jnp.ndarray
    ideal_theta: jnp.ndarray
    initial_chi: jnp.ndarray

@jax.tree_util.register_dataclass
@dataclass(frozen=True)
class HostEmbeddings:
    """Structural conditionings generated by the native Evoformer trunk."""
    pair: jnp.ndarray
    single: jnp.ndarray
    target_feat: Dict[str, jnp.ndarray]

@jax.tree_util.register_dataclass
@dataclass(frozen=True)
class AtomMapping:
    """Index trackers matching the Host layout to the full complex Oracle."""
    oracle_heavy: jnp.ndarray
    af3_source: jnp.ndarray
    num_oracle_atoms: int

@jax.tree_util.register_dataclass
@dataclass(frozen=True)
class WaterMapping:
    """Index trackers for SO(3) rigid-body water structures."""
    oxygen_source: jnp.ndarray
    h1_target: jnp.ndarray
    h2_target: jnp.ndarray
